services:
   ppbot:
      image: '${IMAGE_NAME}'
      container_name: ppbot
      command: node dist/index.js
      networks:
         - scoresaber-network
      extra_hosts:
         - 'host.docker.internal:host-gateway'
      volumes:
         - type: bind
           source: '${CONFIG_FILE_PPBOT}'
           target: /usr/src/app/.env
      restart: on-failure
      build:
         context: ..
         dockerfile: docker/Dockerfile
networks:
   scoresaber-network:
      name: scoresaber-network
      driver: bridge
